### PR TITLE
use travis apt addon

### PR DESCRIPTION
**Pull request by stephengroat**
also, trusty is now the default

### CODE REVIEW

**Comment by AMDmi3** [comment]
What's the gain from this?

**Comment by stephengroat** [comment]
faster run times, gets off of 'sudo' infra

**Comment by AMDmi3** [comment]
Build time is under 2 minutes anyway, so it does not matter. And I'd greatly prefer to stay on sudo infra as it gives full control on what and how can be installed to the system, without trusted repo and package nonsence.

**Comment by stephengroat** [comment]
no problem

**Pull request closed without merging**
